import type { VideoLesson } from '../../types';

export const teamsVideos: Record<string, VideoLesson> = {
  'm5-intro': {
    id: 'm5-intro',
    title: 'Your AI crew, not one overloaded brain',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Design three roles.',
    slides: [
      {
        id: 'v0-1',
        title: 'Hook',
        narration: 'One mega-chat tries to do every job — and drops balls.',
        durationSec: 15,
        bullets: ['Blob brain', 'Blurred boundaries'],
      },
      {
        id: 'v0-2',
        title: 'Promise',
        narration: 'A tiny AI crew with clear roles beats one overloaded brain.',
        durationSec: 15,
        bullets: ['Specialists', 'Clear lanes'],
      },
      {
        id: 'v0-3',
        title: 'Arc',
        narration: 'After routines comes multi-bot teams — roles, DMs, channels.',
        durationSec: 15,
        bullets: ['Connect ✓', 'Day-to-day ✓', 'Routines ✓', 'Teams now'],
      },
      {
        id: 'v0-4',
        title: 'CTA',
        narration: 'Next: design three roles for a field business.',
        durationSec: 15,
        bullets: ['CTA: Design 3 roles'],
      },
    ],
  },
  'm5-v2': {
    id: 'm5-v2',
    title: 'Message one specialist',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 2,
    cta: 'Send a crisp async ask.',
    slides: [
      {
        id: 'v2-1',
        title: 'One clear ask',
        narration: 'Pick one specialist. Ask one scoped question.',
        durationSec: 20,
        bullets: ['Single target', 'Scoped ask'],
      },
      {
        id: 'v2-2',
        title: 'Async',
        narration: 'They reply later — not a live conference call.',
        durationSec: 20,
        bullets: ['Async replies', 'Keep working'],
      },
      {
        id: 'v2-3',
        title: 'No fan-out',
        narration: 'Don’t wake everyone “just in case.”',
        durationSec: 20,
        bullets: ['No @everyone', 'Confirm-gated writes'],
      },
      {
        id: 'v2-4',
        title: 'CTA',
        narration: 'Send a crisp async ask next.',
        durationSec: 15,
        bullets: ['CTA: DM Job Packets'],
      },
    ],
  },
  'm5-v3': {
    id: 'm5-v3',
    title: 'Channels & seating',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 2,
    cta: 'Stand up a project room.',
    slides: [
      {
        id: 'v3-1',
        title: 'Project room',
        narration: 'A channel holds shared project context for one job.',
        durationSec: 20,
        bullets: ['Named room', 'Shared context'],
      },
      {
        id: 'v3-2',
        title: 'Seat who matters',
        narration: 'Seat Scheduler + Packets — Estimator optional.',
        durationSec: 20,
        bullets: ['≥2 members', 'Right specialists'],
      },
      {
        id: 'v3-3',
        title: 'One kickoff',
        narration: 'One kickoff post — not five redundant pings.',
        durationSec: 20,
        bullets: ['Thursday install', 'Contract check'],
      },
      {
        id: 'v3-4',
        title: 'CTA',
        narration: 'Stand up Van Singel Install next.',
        durationSec: 15,
        bullets: ['CTA: Create channel'],
      },
    ],
  },
  'm5-v4': {
    id: 'm5-v4',
    title: 'CoS patterns & fan-out rules',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 2,
    cta: 'Practice assignment without spam.',
    slides: [
      {
        id: 'v4-1',
        title: 'Assign',
        narration: 'Chief of Staff assigns; specialists deliver.',
        durationSec: 22,
        bullets: ['CoS assigns', 'Specialists deliver'],
      },
      {
        id: 'v4-2',
        title: 'Human decides',
        narration: 'Human confirms consequential client-facing actions.',
        durationSec: 23,
        bullets: ['Confirm before email', 'Confirm before calendar write'],
      },
      {
        id: 'v4-3',
        title: 'No spam',
        narration: 'No fan-out, no private vents relayed verbatim.',
        durationSec: 22,
        bullets: ['Scoped pings only', 'Vents stay private'],
      },
      {
        id: 'v4-4',
        title: 'CTA',
        narration: 'Tag OK vs Don’t on fan-out cards.',
        durationSec: 23,
        bullets: ['CTA: No-spam drill'],
      },
    ],
  },
  'm5-outro': {
    id: 'm5-outro',
    title: 'Next: skills & custom tools',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Pass quiz; next Skills.',
    slides: [
      {
        id: 'vo-1',
        title: 'Recap',
        narration: 'Roles, one DM, a seated channel, coordinate without spam.',
        durationSec: 15,
        bullets: ['Roles', 'DM', 'Channel', 'CoS'],
      },
      {
        id: 'vo-2',
        title: 'Next module',
        narration: 'Next: Skills & custom tools so every bot shares playbooks.',
        durationSec: 15,
        bullets: ['Module 6: Skills & Custom Tools'],
      },
      {
        id: 'vo-3',
        title: 'CTA',
        narration: 'Pass the quiz; next deepen with Skills & Custom Tools.',
        durationSec: 15,
        bullets: ['80% to pass', 'Next: Skills'],
      },
    ],
  },
};
