import type { Quiz } from '../../types';

/** 10 questions · pass >= 8/10 (passScore 0.8) */
export const m6Quiz: Quiz = {
  id: 'm6-test',
  title: 'Module 6 quiz',
  passScore: 0.8,
  questions: [
    {
      id: 'q1',
      kind: 'mc',
      stem: 'A swarm should optimize for…',
      options: [
        { id: 'A', text: 'Message volume and chatter' },
        { id: 'B', text: 'Checkable outcomes, not message volume' },
        { id: 'C', text: 'Waking every bot on day one' },
        { id: 'D', text: 'Silent client texts' },
      ],
      correctOptionId: 'B',
      explanation: 'Checkable outcomes, not message volume.',
    },
    {
      id: 'q2',
      kind: 'mc',
      stem: 'Minimum viable swarm includes…',
      options: [
        { id: 'A', text: 'Every bot you ever created' },
        { id: 'B', text: 'Owner/CoS + few specialists + skills + only needed routines' },
        { id: 'C', text: 'Slack webhooks only' },
        { id: 'D', text: 'No skills and no routines' },
      ],
      correctOptionId: 'B',
      explanation: 'Owner/CoS + few specialists + skills + only needed routines.',
    },
    {
      id: 'q3',
      kind: 'mc',
      stem: 'Client texts and calendar edits need…',
      options: [
        { id: 'A', text: 'Silent auto-send' },
        { id: 'B', text: 'Human confirmation' },
        { id: 'C', text: 'Fan-out to every bot' },
        { id: 'D', text: 'Deleting all skills first' },
      ],
      correctOptionId: 'B',
      explanation: 'Human confirmation for client-facing and calendar/Drive writes.',
    },
    {
      id: 'q4',
      kind: 'mc',
      stem: 'Success checks should be…',
      options: [
        { id: 'A', text: 'Vague vibes' },
        { id: 'B', text: 'Binary / observable' },
        { id: 'C', text: 'Measured in message count' },
        { id: 'D', text: 'Optional forever' },
      ],
      correctOptionId: 'B',
      explanation: 'Binary / observable checks.',
    },
    {
      id: 'q5',
      kind: 'mc',
      stem: 'After the job…',
      options: [
        { id: 'A', text: 'Leave every routine running forever' },
        { id: 'B', text: 'Tear down or pause what you do not need; keep reusable skills' },
        { id: 'C', text: 'Delete all skills' },
        { id: 'D', text: 'Require Slack teardown' },
      ],
      correctOptionId: 'B',
      explanation: 'Pause/tear down unused pieces; keep reusable skills.',
    },
    {
      id: 'q6',
      kind: 'mc',
      stem: 'Fan-out to every bot on day one…',
      options: [
        { id: 'A', text: 'Do it always' },
        { id: 'B', text: 'Do not' },
        { id: 'C', text: 'Only via Slack' },
        { id: 'D', text: 'Instead of writing an outcome' },
      ],
      correctOptionId: 'B',
      explanation: 'Do not fan out to every bot on day one.',
    },
    {
      id: 'q7',
      kind: 'short',
      stem: 'Name the loop stages (kickoff -> …).',
      shortRubric: ['kickoff', 'assign', 'gather', 'decide', 'act', 'retrospect', 'retro', 'confirm'],
      explanation: 'kickoff, assign, gather, decide, act, retrospect (rubric >=4).',
    },
    {
      id: 'q8',
      kind: 'mc',
      stem: 'Slack is required for swarms…',
      options: [
        { id: 'A', text: 'True — swarms only work in Slack' },
        { id: 'B', text: 'False — Grok channels; Slack stub for others' },
        { id: 'C', text: 'True — must webhook first' },
        { id: 'D', text: 'True — otherwise teardown fails' },
      ],
      correctOptionId: 'B',
      explanation: 'False — Grok channels; Slack stays stub.',
    },
    {
      id: 'q9',
      kind: 'mc',
      stem: 'Skills in a swarm provide…',
      options: [
        { id: 'A', text: 'Extra noise with no playbook' },
        { id: 'B', text: 'Shared playbooks so specialists do not drift' },
        { id: 'C', text: 'Silent homeowner sends' },
        { id: 'D', text: 'A reason to skip confirm' },
      ],
      correctOptionId: 'B',
      explanation: 'Shared playbooks so specialists do not drift.',
    },
    {
      id: 'q10',
      kind: 'mc',
      stem: 'Series arc complete when you can…',
      options: [
        { id: 'A', text: 'Only connect GitHub forever' },
        { id: 'B', text: 'connect -> daily use -> routines -> teams -> skills -> outcome swarm with guardrails' },
        { id: 'C', text: 'Require Slack before any work' },
        { id: 'D', text: 'Skip human confirm forever' },
      ],
      correctOptionId: 'B',
      explanation: 'connect -> daily use -> routines -> teams -> skills -> outcome swarm with guardrails.',
    },
  ],
};
