import type { VideoLesson } from '../../types';

export const githubVideos: Record<string, VideoLesson> = {
  'm1-intro': {
    id: 'm1-intro',
    title: 'Why Grok Bot + GitHub',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Next: connect and verify.',
    slides: [
      {
        id: 'v0-1',
        title: 'You already live in PRs',
        narration: 'You already live in PRs. Put Grok Bot next to them.',
        durationSec: 12,
        bullets: ['Reviews, CI, and digests without tab thrash'],
      },
      {
        id: 'v0-2',
        title: 'Connect once',
        narration: 'Connect once — then summarize, review, and babysit from chat.',
        durationSec: 18,
        bullets: ['Summarize PRs', 'Structured reviews', 'Event-driven babysitters'],
      },
      {
        id: 'v0-3',
        title: 'Module 1 of Grok Bot + *',
        narration: 'This is Module 1 of Grok Bot + star. GitHub today; Google and Slack later.',
        durationSec: 18,
        bullets: ['Series: grok-bot-plus', 'Built for specialists on the go'],
      },
      {
        id: 'v0-4',
        title: 'Ready?',
        narration: 'Next up: connect and verify the GitHub connector.',
        durationSec: 12,
        bullets: ['CTA: Connect and verify'],
      },
    ],
  },
  'm1-v2': {
    id: 'm1-v2',
    title: 'Day-to-day: PRs in chat',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 2,
    cta: 'Your turn in the practice drill.',
    slides: [
      {
        id: 'v2-1',
        title: "What's open?",
        narration: 'Start with a simple ask: what pull requests are open for me?',
        durationSec: 15,
        bullets: ['List open PRs from chat'],
      },
      {
        id: 'v2-2',
        title: 'Five-bullet digest',
        narration: 'Summarize PR hash N — intent, key files, risks, test plan, what is left.',
        durationSec: 20,
        bullets: ['Intent', 'Key files', 'Risks', 'Test plan', "What's left"],
      },
      {
        id: 'v2-3',
        title: 'Why is CI red?',
        narration: 'Ask why CI is red and get the failing check named clearly.',
        durationSec: 20,
        bullets: ['Name failing checks', 'No need to open the Actions tab'],
      },
      {
        id: 'v2-4',
        title: 'Scope tip',
        narration: 'If results look empty, name owner slash repo explicitly.',
        durationSec: 20,
        bullets: ['Tip: name owner/repo when empty'],
      },
    ],
  },
  'm1-v3': {
    id: 'm1-v3',
    title: 'Ask for a review (safely)',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Practice the safe review loop.',
    slides: [
      {
        id: 'v3-1',
        title: 'Bad ask',
        narration: 'Bad ask: just approve it. That skips judgment and writes to GitHub too early.',
        durationSec: 12,
        bullets: ['Avoid auto-approve prompts'],
      },
      {
        id: 'v3-2',
        title: 'Good ask',
        narration: 'Good ask: focus on correctness, security, tests — chat only, do not post.',
        durationSec: 18,
        bullets: ['Focus areas', 'Chat only until you confirm'],
      },
      {
        id: 'v3-3',
        title: 'Draft the comment',
        narration: 'Turn the top finding into a polite draft comment you could post.',
        durationSec: 15,
        bullets: ['Findings + severity', 'Polite draft'],
      },
      {
        id: 'v3-4',
        title: 'Confirm before write',
        narration: 'Confirm before any write — comment, approve, or merge.',
        durationSec: 15,
        bullets: ['Read-first', 'Confirm before mutate'],
      },
    ],
  },
  'm1-v4': {
    id: 'm1-v4',
    title: 'Automate with a PR babysitter',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 2,
    cta: 'Build yours in the next lesson.',
    slides: [
      {
        id: 'v4-1',
        title: 'The pain',
        narration: 'Pain: you miss a review request or a CI flip while you are away from the desk.',
        durationSec: 18,
        bullets: ['Missed review requests', 'CI flips unnoticed'],
      },
      {
        id: 'v4-2',
        title: 'Watch this PR',
        narration: 'Ask Grok Bot to watch this PR for reviews, pushes, and CI.',
        durationSec: 22,
        bullets: ['review-*', 'pr-pushed', 'ci-passed / ci-failed'],
      },
      {
        id: 'v4-3',
        title: 'Useful ping',
        narration: 'A good ping says what changed and one recommended next action.',
        durationSec: 25,
        bullets: ['What changed', 'One next action'],
      },
      {
        id: 'v4-4',
        title: 'Self-delete',
        narration: 'The routine should delete itself when the PR merges or closes.',
        durationSec: 25,
        bullets: ['Terminal events: merge / close'],
      },
    ],
  },
  'm1-outro': {
    id: 'm1-outro',
    title: "What's next",
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Pass the quiz, then pick your next +.',
    slides: [
      {
        id: 'vo-1',
        title: 'Recap',
        narration: 'Recap: connect, read, review, routine — with confirmations before writes.',
        durationSec: 15,
        bullets: ['Connect → Read → Review → Routine'],
      },
      {
        id: 'vo-2',
        title: 'Next modules',
        narration: 'Module 2 options: Grok Bot plus Google, or Grok Bot plus Slack.',
        durationSec: 15,
        bullets: ['Google (coming soon)', 'Slack (coming soon)'],
      },
      {
        id: 'vo-3',
        title: 'Your move',
        narration: 'Pass the quiz, then pick your next plus.',
        durationSec: 15,
        bullets: ['80% to pass', 'Retry anytime'],
      },
    ],
  },
};
