import type { VideoLesson } from '../../types';

export const skillsVideos: Record<string, VideoLesson> = {
  'm6-intro': {
    id: 'm6-intro',
    title: 'Playbooks > repeating yourself',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Sort skill vs routine vs once.',
    slides: [
      {
        id: 'v0-1',
        title: 'Hook',
        narration: 'Stop retyping the same steps every morning.',
        durationSec: 15,
        bullets: ['Same brief again', 'Same packet check again'],
      },
      {
        id: 'v0-2',
        title: 'Promise',
        narration: 'Skills are reusable playbooks any bot can run.',
        durationSec: 15,
        bullets: ['When-to-use', 'Body + constraints'],
      },
      {
        id: 'v0-3',
        title: 'Arc',
        narration: 'After teams comes shared playbooks — sort, author, wire, harden.',
        durationSec: 15,
        bullets: ['Connect ✓', 'Routines ✓', 'Teams ✓', 'Skills now'],
      },
      {
        id: 'v0-4',
        title: 'CTA',
        narration: 'Next: tell skill vs routine vs once.',
        durationSec: 15,
        bullets: ['CTA: Sort cards'],
      },
    ],
  },
  'm6-v2': {
    id: 'm6-v2',
    title: 'Anatomy of a good skill',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 2,
    cta: 'Author field-job-brief.',
    slides: [
      {
        id: 'v2-1',
        title: 'When-to-use',
        narration: 'Description answers when to use this — not a vague label.',
        durationSec: 20,
        bullets: ['Sharp description', 'Not “stuff”'],
      },
      {
        id: 'v2-2',
        title: 'Body',
        narration: 'Steps, constraints, outputs — timezone, quiet rules, format.',
        durationSec: 20,
        bullets: ['Steps', 'Constraints', 'Outputs'],
      },
      {
        id: 'v2-3',
        title: 'Gates',
        narration: 'Confirm-before-write and NO_EVENTS quiet rules live in the body.',
        durationSec: 20,
        bullets: ['Read-only default', 'Quiet when empty'],
      },
      {
        id: 'v2-4',
        title: 'CTA',
        narration: 'Author field-job-brief next.',
        durationSec: 15,
        bullets: ['CTA: Save skill'],
      },
    ],
  },
  'm6-v3': {
    id: 'm6-v3',
    title: 'Share playbooks across bots',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 2,
    cta: 'Point the team at one skill.',
    slides: [
      {
        id: 'v3-1',
        title: 'One brief',
        narration: 'Scheduler and Packets call the same field brief.',
        durationSec: 20,
        bullets: ['Same playbook', 'Clearer handoffs'],
      },
      {
        id: 'v3-2',
        title: 'CoS assigns once',
        narration: 'Chief of Staff points specialists at [field-job-brief] once.',
        durationSec: 20,
        bullets: ['CoS assigns', 'Specialists follow'],
      },
      {
        id: 'v3-3',
        title: 'No fan-out',
        narration: 'Don’t wake unrelated bots for a morning brief.',
        durationSec: 20,
        bullets: ['Scoped seats', 'Named skill'],
      },
      {
        id: 'v3-4',
        title: 'CTA',
        narration: 'Wire Crew Scheduler + Job Packets next.',
        durationSec: 15,
        bullets: ['CTA: Wire team'],
      },
    ],
  },
  'm6-v4': {
    id: 'm6-v4',
    title: 'Dangerous skills & fixes',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Harden auto-text-clients; delete junk.',
    slides: [
      {
        id: 'v4-1',
        title: 'Vague + silent send',
        narration: 'Vague skills that auto-message clients are dangerous.',
        durationSec: 15,
        bullets: ['description: stuff', 'Silent client texts'],
      },
      {
        id: 'v4-2',
        title: 'Rewrite',
        narration: 'Draft-only, human confirm, no unrelated folder scraping.',
        durationSec: 15,
        bullets: ['Draft + confirm', 'Clear when-to-use'],
      },
      {
        id: 'v4-3',
        title: 'Delete junk',
        narration: 'Delete tmp-skill-test; Cursor-managed skills stay read-only.',
        durationSec: 15,
        bullets: ['Delete obsolete', 'Read-only managed skills'],
      },
      {
        id: 'v4-4',
        title: 'CTA',
        narration: 'Harden and delete next.',
        durationSec: 15,
        bullets: ['CTA: Harden drill'],
      },
    ],
  },
  'm6-outro': {
    id: 'm6-outro',
    title: 'Next: outcome swarms',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Pass quiz; next Swarms.',
    slides: [
      {
        id: 'vo-1',
        title: 'Recap',
        narration: 'Sort types, author, wire the team, harden dangerous skills.',
        durationSec: 15,
        bullets: ['Sort', 'Author', 'Wire', 'Harden'],
      },
      {
        id: 'vo-2',
        title: 'Next module',
        narration: 'Next = swarm aimed at a real Thursday install outcome.',
        durationSec: 15,
        bullets: ['Module 7: Outcome swarms'],
      },
      {
        id: 'vo-3',
        title: 'CTA',
        narration: 'Pass the quiz; next Outcome Swarms.',
        durationSec: 15,
        bullets: ['80% to pass', 'Next: Swarms'],
      },
    ],
  },
};
