import type { VideoLesson } from '../../types';

export const slackVideos: Record<string, VideoLesson> = {
  'm3-intro': {
    id: 'm3-intro',
    title: 'Why Slack + Grok Bot on the go',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Connect & verify workspace.',
    slides: [
      {
        id: 'v0-1',
        title: 'Hook',
        narration: 'Truck / jobsite — Slack is noisy; Grok Bot filters.',
        durationSec: 15,
        bullets: ['Noisy channels', 'Phone in the cab'],
      },
      {
        id: 'v0-2',
        title: 'Promise',
        narration: 'Read digests, draft safely, catch weather/cancel keywords.',
        durationSec: 15,
        bullets: ['Summaries', 'Draft → confirm', 'Keyword pings'],
      },
      {
        id: 'v0-3',
        title: 'Audience',
        narration: 'For specialists who live in Slack — optional if you don’t.',
        durationSec: 15,
        bullets: ['Series completeness', 'Not required for everyone'],
      },
      {
        id: 'v0-4',
        title: 'CTA',
        narration: 'Next: connect and verify the workspace.',
        durationSec: 15,
        bullets: ['CTA: Connect Slack'],
      },
    ],
  },
  'm3-v2': {
    id: 'm3-v2',
    title: 'Read channels from chat',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 2,
    cta: 'Summarize #crew-ops.',
    slides: [
      {
        id: 'v2-1',
        title: 'Ask',
        narration: 'Summarize #crew-ops — five bullets.',
        durationSec: 20,
        bullets: ['Decisions', 'Asks', 'Blockers'],
      },
      {
        id: 'v2-2',
        title: 'Structure',
        narration: 'Owners and what’s next round out the digest.',
        durationSec: 20,
        bullets: ['Owners', 'What’s next'],
      },
      {
        id: 'v2-3',
        title: 'Open ask',
        narration: 'Spot the hitch confirmation ask for the crew lead.',
        durationSec: 20,
        bullets: ['Trailer hitch confirmation'],
      },
      {
        id: 'v2-4',
        title: 'CTA',
        narration: 'Summarize #crew-ops next.',
        durationSec: 15,
        bullets: ['CTA: Structured summary'],
      },
    ],
  },
  'm3-v3': {
    id: 'm3-v3',
    title: 'Draft then post (safely)',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Draft before you post.',
    slides: [
      {
        id: 'v3-1',
        title: 'Draft',
        narration: 'Draft the reply in chat first.',
        durationSec: 15,
        bullets: ['Chat-only draft'],
      },
      {
        id: 'v3-2',
        title: 'Confirm',
        narration: 'Review — then explicit confirm.',
        durationSec: 15,
        bullets: ['Confirm Post sheet'],
      },
      {
        id: 'v3-3',
        title: 'Post',
        narration: 'Only then post to Slack.',
        durationSec: 15,
        bullets: ['No blind auto-post'],
      },
      {
        id: 'v3-4',
        title: 'CTA',
        narration: 'Practice draft-before-post.',
        durationSec: 15,
        bullets: ['CTA: Draft then confirm'],
      },
    ],
  },
  'm3-v4': {
    id: 'm3-v4',
    title: '“Ping me when…” in Slack',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 2,
    cta: 'Build weather/cancel routine.',
    slides: [
      {
        id: 'v4-1',
        title: 'Keywords',
        narration: 'Keyword cancel or weather → phone ping.',
        durationSec: 25,
        bullets: ['weather', 'cancel'],
      },
      {
        id: 'v4-2',
        title: 'Digest',
        narration: 'Author, text, one next action — not spam every message.',
        durationSec: 25,
        bullets: ['Author + text', 'One next action'],
      },
      {
        id: 'v4-3',
        title: 'Quiet',
        narration: 'Ignore other messages; don’t auto-reply in channel.',
        durationSec: 20,
        bullets: ['Channel scoped', 'No auto-reply'],
      },
      {
        id: 'v4-4',
        title: 'CTA',
        narration: 'Build the weather/cancel routine.',
        durationSec: 20,
        bullets: ['CTA: Keyword routine'],
      },
    ],
  },
  'm3-outro': {
    id: 'm3-outro',
    title: 'Next: Module 4 — Routines',
    type: 'video',
    depths: ['skim', 'solid', 'deep'],
    estMinutes: 1,
    cta: 'Pass quiz; deepen with Routines.',
    slides: [
      {
        id: 'vo-1',
        title: 'Recap',
        narration: 'Connect → read → draft/confirm post → keyword routine → safe norms.',
        durationSec: 15,
        bullets: ['Connect', 'Read', 'Write safely', 'Routine'],
      },
      {
        id: 'vo-2',
        title: 'Next module',
        narration: 'Next deepen with Routines; Teams for multi-bot later.',
        durationSec: 15,
        bullets: ['Module 4: Routines'],
      },
      {
        id: 'vo-3',
        title: 'CTA',
        narration: 'Pass the quiz; ship crew-ops safely.',
        durationSec: 15,
        bullets: ['80% to pass', 'Next: Routines'],
      },
    ],
  },
};
